ARG NIGHTLY_DATE="20241017"
ARG BASE_IMAGE="us-central1-docker.pkg.dev/tpu-pytorch-releases/docker/xla:nightly_3.10_tpuvm_$NIGHTLY_DATE"

FROM $BASE_IMAGE
WORKDIR /workspace

# Install some basic utilities
RUN apt-get update && apt-get install -y \
    git \
    ffmpeg libsm6 libxext6 libgl1
RUN apt-get install -y libopenblas-base libopenmpi-dev libomp-dev

# Install the TPU and Pallas dependencies.
#RUN --mount=type=cache,target=/root/.cache/pip \
#    python3 -m pip install torch_xla[tpu] -f https://storage.googleapis.com/libtpu-releases/index.html
#RUN --mount=type=cache,target=/root/.cache/pip \
#    python3 -m pip install torch_xla[pallas] -f https://storage.googleapis.com/jax-releases/jax_nightly_releases.html -f https://storage.googleapis.com/jax-releases/jaxlib_nightly_releases.html
RUN pip3 install setuptools_scm
RUN pip3 install --pre torch==2.6.0.dev20240913+cpu torchvision==0.20.0.dev20240913+cpu --index-url https://download.pytorch.org/whl/nightly/cpu
# Install JAX and Pallas.
RUN pip3 install "torch_xla[tpu] @ https://storage.googleapis.com/pytorch-xla-releases/wheels/tpuvm/torch_xla-2.6.0.dev20240913-cp310-cp310-linux_x86_64.whl" -f https://storage.googleapis.com/libtpu-releases/index.html
RUN pip3 install https://storage.googleapis.com/libtpu-nightly-releases/wheels/libtpu-nightly/libtpu_nightly-0.1.dev20240913+nightly-py3-none-any.whl
RUN pip3 install torch_xla[pallas] -f https://storage.googleapis.com/jax-releases/jax_nightly_releases.html -f https://storage.googleapis.com/jax-releases/jaxlib_nightly_releases.html
RUN pip3 install -U "ray[default] @ https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-3.0.0.dev0-cp310-cp310-manylinux2014_x86_64.whl"

# Build vLLM.
#COPY ./vllm/. /workspace/vllm
RUN git clone -b dev https://github.com/allenwang28/vllm.git /workspace/vllm

ENV VLLM_TARGET_DEVICE="tpu"
RUN cd /workspace/vllm && \
    python3 -m pip install \
        cmake>=3.26 ninja packaging setuptools-scm>=8 wheel jinja2 \
        -r requirements-tpu.txt
RUN cd /workspace/vllm && python3 setup.py develop

CMD ["/bin/bash"]
